### ISSUE TITLE
Rugby Council Broken

### ISSUE THREAD

**Issue by matt0020190** [robbrad/UKBinCollectionData#1316]
### Home Assistant Version

2025.4 2

### Installation Method

Using HACS

### Name of Council (if relevant)

Rugby borough Council

### Issue Information

Since a recent update,  the entities won't load anymore with error as follows:

Failed setup, will retry: Unexpected error: 'NoneType' object has no attribute 'find'

### Verification

- [x] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [x] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [x] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [x] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by davida72** [comment]
They seem to have switched to a new system. I've fixed this using Selenium, but their site is currently not displaying bin collection info when you choose an address so I can't test it.

**Comment by robbrad** [comment]
URL : https://www.rugby.gov.uk/check-your-next-bin-day

**Comment by robbrad** [comment]
![Image](https://github.com/user-attachments/assets/65f9529b-bb30-4154-894b-1ebb7243c218)

Sample Address :  7 LYDDEN CLOSE RUGBY CV21 1AH

**Comment by matt0020190** [comment]
Latest update today still an issue,  same error.  As per above,  my URL is the same and I can see my collection days too

**Comment by robbrad** [comment]
We are working on it @matt0020190

**Comment by matt0020190** [comment]
Hi, upgraded to 151 and this error:
Failed setup, will retry: Unexpected error: [Errno 2] No such file or directory: '/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver'
